### ISSUE TITLE
Question on the intention of siege

### ISSUE THREAD

**Issue by Certiman** [tversteeg/siege#1]
(Will write in English, but I'm speaking Dutch too)
Hi Thomas, coincidentally I was currently looking for a Rust based 2D engine, for the same objective as you seem to have with siege: horizontal 2D games with forward and backward scenery; gravity, collision, etc. and two battling camps. 

Could you describe the main goals of the siege collection of code? 

Is siege going to distinguish or foresee the following:

- non-mobile objects (trees; rocks; etc) fixed on the frontal scene, until they get hit and thrown away. They also have the property of slowing down or even making impossible passing-by of other mobile objects, including projectiles.
- moving objects, like players and mobile enemies. Some of these are not connected to the forward scene, meaning they could fly for a certain while (but differently than the projectile object).
- steepness dependent speeds (and zero for some mobile objects like catapults)
- unpassable areas in the scene (lakes, seas), which would require pontons or bridge structures to be built
- AI on one of the camps (computer plays)
- Multi-functional characters (soldiers, builders, etc) to assist in modifying the scene and the siege circumstances?

My apologies if this is not what you want to achieve with siege of course. Thanks for any info.

**Comment by tversteeg** [comment]
Hi! The *siege* library is going to be a library made for my [*castle-game*](https://github.com/tversteeg/castle-game) project. The intent of the library is to design pixel art siege weaponry with the *siege-editor* using primitives and render them on a pixel buffer. The reason I do this and not just draw them is that the lines can then easily be rotated, animated and optionally have dynamic lighting.

The problems you adressed will mostly be things that I will (or won't in some cases) solve in *castle-game*. The [TODO list](https://github.com/tversteeg/castle-game/projects/1) might answer some of your questions because I'm in a bit of a hurry today. If you have any further questions you can ask them in the [Riot chat room](https://riot.im/app/#/room/#castle-game:matrix.org).

**Comment by tversteeg** [comment]
After 2 years I'm readjusting the scope of this project a bit. I've decided to move castle-game forward but instead of using pixel art I'll make an attempt at implementing vector rendering using the awesome lyon crate.

The role of this crate will be simple: it will facilitate in procedureally generating siege engines inspired by [this Ludum Dare entry](https://mike-mezhenin.itch.io/keep-calm).

I have the following steps for that in mind:

- Define basic building blocks of a siege engine, for example the base with wheels, a platform for archers, etc.
- Create a structure of those blocks using wave function collapse.
- Verify basic physics by asserting that the center of mass is low enough.
- Drawing the actual structure using simple drawing primitives for parts of a block such as a line for a beam.

I'm not sure this will succeed or keep my attention for long enough but I'll give it a shot. No promises though!
